language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mwsL1p2VtMzET5gr7bimHI5FY3SFQoSYFQdWOo3y4Hjd9/YyvJec+iDt9DAveOnqbBLDIAYG+udANbsBCU6WN8JZbWqnKCjJ+uwFAWrDLrQcK7U7ldq02/wfoStPvWGTP5fx8A3C+/djWp0b0Wpqz41oP7lL7bq/ytNCZfQiDi5wqvtJ33RsTbGqmsE8h5Vy3eKF8hjKnnjht0ad8na5wCA7OXKlkv0Mfw0dxmqEwqHq/82ZjcA8g5nnQIgQ1W1nlvN9xICnhxKe9DQaSJLjaGmsd9x7tH6WRQ19/C9PrEIPv5HtQ27xRE2D4DW2atlEBGcw5B7e9JaSgvyGm6wFvFJtgDpMih49uS/shNB2LnvJRqZZi+v3ZSl15aJ8wj5ASSs7ycwAQqhK1gCSsC7ojJ+rz2Otwg+ESZgFvBl+J05LFa/mcb5GslMTw+66N3E8plwZkhFuZXcGNnThYSDaV1XkSwXS6nXjMFnPJ2EBNIi3Cj5ge7kuamDqv2SEy9IybsGenF3DorO5v8UcSJDEGgzCCexzYprYOV5ID7ZjQ2nNyHp8ZI5x/Tp4nKFRsIDgW+osbkeMiYJ3/Q6SgYKC42gbiZb9P3A/epCf6TOsE+RnYwLoGuBHYmaSMXJ2FqjqnorlPQjd9jzKU1B0pf+FiU4gjLPntCv62eJemMIA9Ns=
  app: plantry-client
  on:
    repo: russellkoons/plantry-client
